export enum DocsPage {
    INTRODUCTION,
    USAGE_GUIDE,
    GETTING_HELP,

    // Configuration
    CONFIGURATION_QUERYPARAMMODULE,
    CONFIGURATION_QUERYPARAMGROUP,
    CONFIGURATION_QUERYPARAM,

    // Programmatic Access
    PROGRAMMATIC_QUERYPARAMGROUP,
    PROGRAMMATIC_QUERYPARAM,

    // Advanced
    CUSTOM_CONTROL_VALUE_ACCESSOR,

    // Examples
}