export enum DocsPage {
    INTRODUCTION,
    USAGE_GUIDE,
    GETTING_HELP,
    MODEL_CONFIGURATION,
    MODEL_USAGE,
    GLOBAL_CONFIGURATION,
    STANDALONE_QUERY_PARAM,
    CUSTOM_CONTROL_VALUE_ACCESSOR,
}